### ISSUE TITLE
big image expanded to the edge of browser window 

### ISSUE THREAD

**Issue by kenng** [ksylvest/jquery-lighter#10]
Thanks for creating the plugin! 

One improvement that I think would be great is to limit the maximum height of the image, so it will not expanded to the edge of browser window. As when this happen, the close button become invisible and the overall look is discounted, best is to keep it below 80% of the actual window height. Better if we can specify the maximum height in the option. 

Image example that I use is 1280x960.

**Comment by ksylvest** [comment]
@kenng Can't seem to reproduce this bug. Every time I try resizing the demo (http://ksylvest.github.io/jquery-lighter/) it stays within the confines of the screen. Can you attach a screenshot and add some more reproduction steps?

**Comment by kenng** [comment]
@ksylvest tested again and realized it was due to missing <!DOCTYPE html>, which resulted in wrong $(window).height(). So it's a false alarm. Thanks!
