### ISSUE TITLE
Lighter has not open with faded shadow in IE8 issue

### ISSUE THREAD

**Issue by Raghava525** [ksylvest/jquery-lighter#12]
The lighter pop up with image has displayed in Mozilla and Chrome successfully. But there is a issue in IE8 . The lighter pop have not open and there is a "X" mark on the image which is on clicked.....

**Comment by ksylvest** [comment]
@Raghava525 Thanks for the bug report. If you have a pull request with a fix feel free to reopen and I'll review and merge. I don't have any desire to support legacy IE otherwise.
